<?php defined( 'ABSPATH' ) || exit; ?>
<section class="krev-orders">
	<header class="krev-page-header krev-heading-row"><div><p class="krev-eyebrow"><?php esc_html_e( 'Marketplace', 'kniferevive-seller-orders' ); ?></p><h2><?php esc_html_e( 'Seller Orders', 'kniferevive-seller-orders' ); ?></h2></div><a class="krev-account-return" href="<?php echo esc_url( wc_get_page_permalink( 'myaccount' ) ); ?>" aria-label="<?php esc_attr_e( 'My Account', 'kniferevive-seller-orders' ); ?>"><svg aria-hidden="true" viewBox="0 0 24 24" focusable="false"><circle cx="12" cy="8" r="3.5"></circle><path d="M4.5 20c.6-4 3.2-6 7.5-6s6.9 2 7.5 6"></path></svg><span><?php esc_html_e( 'My Account', 'kniferevive-seller-orders' ); ?></span></a></header>
	<nav class="krev-tabs" aria-label="<?php esc_attr_e( 'Seller order filters', 'kniferevive-seller-orders' ); ?>">
		<?php foreach ( array( 'needs-fulfillment' => 'Needs Fulfillment', 'local-pickup' => 'Local Pickup', 'returns' => 'Returns', 'completed' => 'Completed', 'cancelled-refunded' => 'Cancelled / Refunded', 'all' => 'All' ) as $key => $label ) : ?>
			<a class="<?php echo $tab === $key ? 'is-active' : ''; ?>" href="<?php echo esc_url( add_query_arg( 'tab', $key, wc_get_account_endpoint_url( 'seller-orders' ) ) ); ?>"><?php echo esc_html( $label ); ?></a>
		<?php endforeach; ?>
	</nav>
	<div class="krev-order-cards krev-order-list">
		<?php if ( empty( $appointment_cards ) && empty( $result->orders ) && ( ! $sharpening_result || empty( $sharpening_result->orders ) ) ) : ?><p class="woocommerce-info"><?php esc_html_e( 'No seller orders match this filter.', 'kniferevive-seller-orders' ); ?></p><?php endif; ?>
		<?php foreach ( $appointment_cards as $appointment ) : ?>
			<article class="krev-card krev-booking-card">
				<div class="krev-card-heading"><div><span><?php echo esc_html( sprintf( 'Sharpening booking · Order #%s', $appointment['order_number'] ) ); ?></span><small><?php echo esc_html( 'Local Pickup · ' . ( $appointment['handoff'] ?? 'Customer drop-off and collection' ) ); ?></small></div><span class="krev-status"><?php echo esc_html( $appointment['state'] ); ?></span></div>
				<div class="krev-row-items"><?php foreach ( $appointment['items'] as $service ) : ?><div class="krev-product-line"><strong><?php echo esc_html( $service ); ?></strong></div><?php endforeach; ?></div>
				<dl><div><dt><?php esc_html_e( 'Service day (Pacific)', 'kniferevive-seller-orders' ); ?></dt><dd><?php echo esc_html( $appointment['date'] ); ?></dd></div><div><dt><?php esc_html_e( 'Payment', 'kniferevive-seller-orders' ); ?></dt><dd><?php echo esc_html( $appointment['payment'] ); ?></dd></div><div><dt><?php esc_html_e( 'Order total', 'kniferevive-seller-orders' ); ?></dt><dd><?php echo esc_html( $appointment['total'] ); ?></dd></div><div><dt><?php esc_html_e( 'WooCommerce status', 'kniferevive-seller-orders' ); ?></dt><dd><?php echo esc_html( $appointment['order_status'] ); ?></dd></div></dl>
				<div class="krev-row-action"><a class="button krev-primary-action" href="<?php echo esc_url( $appointment['review_url'] ); ?>"><?php esc_html_e( 'Review booking', 'kniferevive-seller-orders' ); ?></a></div>
			</article>
		<?php endforeach; ?>
		<?php if ( $sharpening_result ) : foreach ( $sharpening_result->orders as $sharpening_order ) : $sharpening = KREV_Sharpening_Workflow::dto( $sharpening_order ); $current = current( array_filter( $sharpening['stages'], static function( $stage ) { return 'current' === $stage['state']; } ) ); ?>
			<article class="krev-card krev-order-row krev-sharpening-card"><div class="krev-card-heading"><div><span><?php echo esc_html( sprintf( 'Knife Sharpening #%s', $sharpening['order_number'] ) ); ?></span><small><?php esc_html_e( 'Local Pickup', 'kniferevive-seller-orders' ); ?></small></div><span class="krev-status"><?php echo esc_html( $current['label'] ?? __( 'Completed', 'kniferevive-seller-orders' ) ); ?></span></div><div class="krev-row-items"><div class="krev-product-line"><?php if ( $current ) : ?><img src="<?php echo esc_url( $current['icon'] ); ?>" alt=""><div><strong><?php echo esc_html( $current['label'] ); ?></strong><span><?php echo esc_html( sprintf( _n( '%d sharpening service', '%d sharpening services', count( $sharpening['services'] ), 'kniferevive-seller-orders' ), count( $sharpening['services'] ) ) ); ?></span></div><?php endif; ?></div></div><dl><div><dt><?php esc_html_e( 'Workflow', 'kniferevive-seller-orders' ); ?></dt><dd><?php esc_html_e( 'Sharpening', 'kniferevive-seller-orders' ); ?></dd></div><div><dt><?php esc_html_e( 'Handoff', 'kniferevive-seller-orders' ); ?></dt><dd><?php echo esc_html( $sharpening['handoff'] ?: '—' ); ?></dd></div></dl><div class="krev-row-action"><a class="button krev-primary-action" href="<?php echo esc_url( trailingslashit( wc_get_account_endpoint_url( 'sharpening-orders' ) ) . $sharpening_order->get_id() . '/' ); ?>"><?php esc_html_e( 'View Order', 'kniferevive-seller-orders' ); ?></a></div></article>
		<?php endforeach; endif; ?>
		<?php foreach ( $result->orders as $order ) : try { $dto = KREV_Orders_Reader::dto( $order ); } catch ( Throwable $error ) { continue; } if ( is_wp_error( $dto ) ) { continue; } ?>
			<article class="krev-card krev-order-row">
				<div class="krev-card-heading"><div><span><?php echo esc_html( sprintf( 'Order #%s', $dto['order_number'] ) ); ?></span><small><?php echo esc_html( $dto['date'] ); ?></small></div><span class="krev-status"><?php echo esc_html( $dto['status_label'] ); ?></span></div>
				<div class="krev-row-items"><?php foreach ( $dto['seller_items'] as $item ) : ?><div class="krev-product-line"><img src="<?php echo esc_url( $item['image'] ); ?>" alt=""><div><strong><?php echo esc_html( $item['title'] ); ?></strong><span><?php echo esc_html( sprintf( 'Qty %d', $item['quantity'] ) ); ?></span></div></div><?php endforeach; ?></div>
				<dl><div><dt><?php esc_html_e( 'Shipping', 'kniferevive-seller-orders' ); ?></dt><dd><?php echo esc_html( $dto['shipping']['method'] ?: '—' ); ?></dd></div><div><dt><?php esc_html_e( 'Tracking', 'kniferevive-seller-orders' ); ?></dt><dd><?php echo esc_html( $dto['tracking'] ? end( $dto['tracking'] )['tracking_number'] : __( 'Not added', 'kniferevive-seller-orders' ) ); ?></dd></div></dl>
				<div class="krev-row-action"><a class="button krev-primary-action" href="<?php echo esc_url( trailingslashit( wc_get_account_endpoint_url( 'seller-orders' ) ) . $order->get_id() . '/' ); ?>"><?php esc_html_e( 'View Order', 'kniferevive-seller-orders' ); ?></a></div>
				<?php include KREV_ORDERS_PATH . 'templates/order-earnings.php'; ?>
			</article>
		<?php endforeach; ?>
	</div>
	<?php if ( $result->max_num_pages > 1 ) : ?><nav class="krev-row-pagination" aria-label="<?php esc_attr_e( 'Seller orders pagination', 'kniferevive-seller-orders' ); ?>"><?php if ( $page > 1 ) : ?><a class="button" href="<?php echo esc_url( add_query_arg( array( 'tab' => $tab, 'orders-page' => $page - 1 ), wc_get_account_endpoint_url( 'seller-orders' ) ) ); ?>">← <?php esc_html_e( 'Previous', 'kniferevive-seller-orders' ); ?></a><?php endif; ?><span><?php echo esc_html( sprintf( __( 'Page %1$d of %2$d', 'kniferevive-seller-orders' ), $page, $result->max_num_pages ) ); ?></span><?php if ( $page < $result->max_num_pages ) : ?><a class="button" href="<?php echo esc_url( add_query_arg( array( 'tab' => $tab, 'orders-page' => $page + 1 ), wc_get_account_endpoint_url( 'seller-orders' ) ) ); ?>"><?php esc_html_e( 'Next', 'kniferevive-seller-orders' ); ?> →</a><?php endif; ?></nav><?php endif; ?>
</section>
