<?php
defined( 'ABSPATH' ) || exit;
$back_url = ! KREV_Orders_Permissions::is_operator() && ! KREV_Orders_Permissions::customer_can_view_order( $order )
	? add_query_arg( 'tab', 'local-pickup', wc_get_account_endpoint_url( 'seller-orders' ) )
	: wc_get_account_endpoint_url( 'sharpening-orders' );
?>
<section class="krev-orders krev-sharpening-detail" data-order-id="<?php echo esc_attr( $sharpening['order_id'] ); ?>">
	<a class="krev-back" href="<?php echo esc_url( $back_url ); ?>">← <?php esc_html_e( 'Back to orders', 'kniferevive-seller-orders' ); ?></a>
	<header class="krev-page-header"><p class="krev-eyebrow"><?php echo esc_html( wc_get_order_status_name( $sharpening['woocommerce_status'] ) ); ?></p><h2><?php echo esc_html( sprintf( 'Knife Sharpening #%s', $sharpening['order_number'] ) ); ?></h2><p><?php echo esc_html( 'paid' === $sharpening['payment_state'] ? __( 'Payment complete', 'kniferevive-seller-orders' ) : __( 'Payment due through WooCommerce / approved POS', 'kniferevive-seller-orders' ) ); ?></p></header>
	<div class="krev-stage-timeline">
		<?php foreach ( $sharpening['stages'] as $stage ) : ?><article class="krev-stage is-<?php echo esc_attr( $stage['state'] ); ?>"><div class="krev-stage-icon"><img src="<?php echo esc_url( $stage['icon'] ); ?>" alt=""></div><div><span><?php echo esc_html( $stage['number'] ); ?></span><strong><?php echo esc_html( $stage['label'] ); ?></strong><small><?php echo esc_html( ucfirst( $stage['state'] ) ); ?></small></div></article><?php endforeach; ?>
	</div>
	<div class="krev-detail-grid"><section class="krev-card"><h3><?php esc_html_e( 'Services', 'kniferevive-seller-orders' ); ?></h3><?php foreach ( $sharpening['services'] as $service ) : ?><p><strong><?php echo esc_html( $service['name'] ); ?></strong><br><?php echo esc_html( sprintf( 'Qty %d', $service['quantity'] ) ); ?></p><?php endforeach; ?></section><section class="krev-card"><h3><?php esc_html_e( 'Handoff & completion', 'kniferevive-seller-orders' ); ?></h3><p><?php echo esc_html( $sharpening['handoff'] ?: __( 'Handoff information has not been recorded yet.', 'kniferevive-seller-orders' ) ); ?></p><?php if ( $sharpening['expected_ready_date'] ) : ?><p><?php echo esc_html( sprintf( __( 'Expected ready date: %s', 'kniferevive-seller-orders' ), $sharpening['expected_ready_date'] ) ); ?></p><?php endif; ?><p><?php echo esc_html( $sharpening['completion_information'] ); ?></p></section></div>
	<?php if ( KREV_Orders_Permissions::is_operator() ) : ?><section class="krev-card krev-operator"><h3><?php esc_html_e( 'Operator controls', 'kniferevive-seller-orders' ); ?></h3><form class="krev-rest-form krev-stage-form"><label><?php esc_html_e( 'Stage', 'kniferevive-seller-orders' ); ?><select name="stage"><?php foreach ( KREV_Sharpening_Assets::stages() as $key => $stage ) : ?><option value="<?php echo esc_attr( $key ); ?>" <?php selected( $key, $sharpening['current_stage'] ); ?>><?php echo esc_html( $stage['number'] . ' ' . $stage['label'] ); ?></option><?php endforeach; ?></select></label><label><?php esc_html_e( 'Internal note', 'kniferevive-seller-orders' ); ?><textarea name="internal_note"></textarea></label><label><?php esc_html_e( 'Handoff method/information', 'kniferevive-seller-orders' ); ?><input name="handoff" value="<?php echo esc_attr( $sharpening['handoff'] ); ?>"></label><label><?php esc_html_e( 'Expected ready date', 'kniferevive-seller-orders' ); ?><input type="date" name="expected_ready_date" value="<?php echo esc_attr( $sharpening['expected_ready_date'] ); ?>"></label><button class="button krev-primary-action" type="submit"><?php esc_html_e( 'Save Stage', 'kniferevive-seller-orders' ); ?></button></form><?php if ( 'return' === $sharpening['current_stage'] && ! $sharpening['workflow_completed'] ) : ?><button class="button krev-primary-action krev-complete-sharpening" type="button"><?php esc_html_e( 'Complete Order', 'kniferevive-seller-orders' ); ?></button><?php endif; ?></section><?php endif; ?>
</section>
