<?php
/** Real native cart/session storage; synthetic products, mail and gateway only. */
ob_start();set_exception_handler(static function(\Throwable $e){fwrite(STDERR,'FAIL: '.$e->getMessage()."\n");exit(1);});
require __DIR__.'/sandbox-bootstrap.php';
use KnifeRevive\AgentCommerce\{Api,Booking,BookingSession,Domain,Fault,Settings,Store,StorefrontBooking};
if(DB_NAME!=='krev_agent_sandbox' || DB_HOST!==KREV_TEST_DB_HOST)throw new RuntimeException('Sandbox fence failed');
$checks=0;function sfCheck($ok,$label){global $checks;if(!$ok)throw new RuntimeException($label);++$checks;echo "PASS: $label\n";}
function sfReject(callable $fn,$code){try{$fn();}catch(Fault $e){sfCheck($e->codeName===$code,'rejects '.$code);return;}throw new RuntimeException('Missing rejection '.$code);}
function sfSave(){WC()->cart->calculate_totals();WC()->session->set('cart',WC()->cart->get_cart_for_session());WC()->session->save_data();}
$admin=get_user_by('login','sandbox-admin')->ID;wp_set_current_user($admin);
$vendor=wp_insert_user(['user_login'=>'storefront-'.Domain::id(),'user_pass'=>Domain::id(),'user_email'=>Domain::id().'@example.invalid','role'=>'seller']);update_user_meta($vendor,'dokan_enable_selling','yes');
$term=get_term_by('slug','knife-sharpening','product_cat');$products=[];
foreach([['Small Knife Sharpening','5',true],['Large Knife Sharpening','7',true],['Ordinary physical product','15',false],['Unconfigured sharpening','9',true]] as [$name,$price,$service]){$p=new WC_Product_Simple();$p->set_name($name);$p->set_status('publish');$p->set_regular_price($price);$p->set_virtual(false);if($service)$p->set_category_ids([$term->term_id]);$p->save();wp_update_post(['ID'=>$p->get_id(),'post_author'=>$vendor]);$products[]=$p;}
[$small,$large,$goods,$unknown]=$products;
class StorefrontTestGateway extends WC_Payment_Gateway{public function __construct(){$this->id='stripe';$this->enabled='yes';$this->supports=['products','refunds'];$this->settings=['testmode'=>'no'];}public function is_available(){return true;}}
add_filter('woocommerce_payment_gateways',static fn()=>[StorefrontTestGateway::class],1000);WC()->payment_gateways()->init();
$zone=new WC_Shipping_Zone();$zone->set_zone_name('Synthetic storefront sharpening');$zone->add_location('US:CA','state');$zone->save();$flat=$zone->add_shipping_method('flat_rate');update_option('woocommerce_flat_rate_'.$flat.'_settings',['enabled'=>'yes','cost'=>'7.99']);$local=$zone->add_shipping_method('local_pickup');update_option('woocommerce_local_pickup_'.$local.'_settings',['enabled'=>'yes','cost'=>'0']);delete_transient('wc_shipping_method_count');WC_Cache_Helper::invalidate_cache_group('shipping_zones');
$s=Settings::validate(['booking_transport_taxable'=>true,'booking_require_payment_submission'=>true,'booking_trip_fee_minor'=>600,'booking_round_trip_fee_minor'=>1100,'booking_enabled'=>true,'booking_prepaid_enabled'=>true,'booking_launch_approved'=>true,'booking_pay_before_confirmation'=>true,'booking_location'=>'Synthetic only','booking_services'=>[['product_id'=>$small->get_id(),'definition'=>'Small knife'],['product_id'=>$large->get_id(),'definition'=>'Large knife']],'booking_daily_capacity'=>200,'booking_weekly_hours'=>[['weekday'=>5,'open'=>'09:00','close'=>'19:00'],['weekday'=>6,'open'=>'09:00','close'=>'19:00'],['weekday'=>7,'open'=>'10:00','close'=>'16:00']],'booking_policy_url'=>'https://kniferevive.com/sharpening-cancellations-and-refunds/','booking_policy_version'=>'synthetic-only','listing_gateway_ids'=>['stripe']]);update_option('krev_agent_settings',$s,false);
update_option('woocommerce_calc_taxes','no');update_option('pisol_cefw_payment_gateway_charges',[]);wc_load_cart();WC()->session->set_customer_session_cookie(true);WC()->session->set('order_awaiting_payment',null);WC()->cart->empty_cart();
$before=(int)$wpdb->get_var('SELECT COUNT(*) FROM '.Store::table('records')." WHERE kind='booking'");
sfCheck(!StorefrontBooking::begin(),'empty cart keeps ordinary checkout');$gkey=WC()->cart->add_to_cart($goods->get_id(),1);sfSave();sfCheck(!StorefrontBooking::begin(),'goods-only cart keeps ordinary checkout');
$ordinary=new WC_Order();$ordinary->add_product($goods,1);StorefrontBooking::guardOrder($ordinary);sfCheck(true,'physical goods order passes native guard');$ordinary->add_product($small,1);sfReject(static fn()=>StorefrontBooking::guardOrder($ordinary),'BOOKING_REQUIRED');
$skey=WC()->cart->add_to_cart($small->get_id(),2);$lkey=WC()->cart->add_to_cart($large->get_id(),1);sfSave();sfCheck(StorefrontBooking::begin(),'mixed sharpening cart enters shared booking');sfCheck(StorefrontBooking::defaults()==[$small->get_id()=>2,$large->get_id()=>1],'small and large quantities prefilled');
ob_start();StorefrontBooking::fields([]);$html=ob_get_clean();preg_match('/name="store_cart_hash" value="([^"]+)"/',$html,$match);$hash=$match[1];sfCheck(str_contains($html,'Your other items stay in your cart'),'mixed cart explains separate purchase');StorefrontBooking::validate(['store_cart_hash'=>$hash]);sfReject(static fn()=>StorefrontBooking::validate([]),'CART_CONFLICT');sfReject(static fn()=>StorefrontBooking::validate(['store_cart_hash'=>'stale']),'CART_CONFLICT');
sfCheck(WC()->cart->get_cart_contents_count()===4,'GET and invalid source checks leave every cart item');sfCheck((int)$wpdb->get_var('SELECT COUNT(*) FROM '.Store::table('records')." WHERE kind='booking'")===$before,'cart discovery creates no booking');
$pending=wc_create_order(['status'=>'pending']);$pending->add_product($small,1);$pending->calculate_totals();$pending->save();WC()->session->set('order_awaiting_payment',$pending->get_id());sfReject(static fn()=>StorefrontBooking::begin(),'CART_CONFLICT');sfCheck(wc_get_order($pending->get_id())->get_status()==='pending','existing pending order unchanged');WC()->session->set('order_awaiting_payment',null);
$ukey=WC()->cart->add_to_cart($unknown->get_id(),1);sfReject(static fn()=>StorefrontBooking::begin(),'SERVICE_REVIEW_REQUIRED');WC()->cart->remove_cart_item($ukey);sfSave();StorefrontBooking::begin();
$owner=Domain::id();Store::put($owner,'session','synthetic',time()+7200,['token_hash'=>hash('sha256',Domain::token($owner))]);$days=Booking::availability()['days'];$date=end($days)['date'];
$base=['items'=>[['product_id'=>$small->get_id(),'quantity'=>3],['product_id'=>$large->get_id(),'quantity'=>1]],'mode'=>'pay_later_dropoff','preferred_date'=>$date];$row=Booking::create($base,$owner,'sf-unpaid-'.Domain::id());sfReject(static fn()=>StorefrontBooking::complete($row),'CART_CONFLICT');
$row=Booking::submit($row['id'],$owner,['customer'=>['name'=>'Synthetic buyer','email'=>'buyer@example.invalid']],true);StorefrontBooking::complete($row);sfCheck(count(WC()->cart->get_cart())===1 && isset(WC()->cart->get_cart()[$gkey]),'unpaid handoff removes only source sharpening lines');sfCheck(Booking::transportFee($row)===0,'unpaid trip fee stays zero');sfCheck(Store::get($row['id'])['data']['source']==='storefront_cart','record identifies storefront entry');sfCheck(count(WC()->session->get('cart'))===1,'ordinary native session persists remaining product');sfCheck(count(get_user_meta($admin,'_woocommerce_persistent_cart_'.get_current_blog_id(),true)['cart'])===1,'logged-in persistent cart cannot restore consumed sharpening');
// A changed source must fail closed even after a recoverable request exists.
WC()->cart->add_to_cart($small->get_id(),1);sfSave();StorefrontBooking::begin();$key=array_key_last(WC()->cart->get_cart());WC()->cart->set_quantity($key,2);sfSave();sfReject(static fn()=>StorefrontBooking::complete($row),'CART_CONFLICT');sfCheck(WC()->cart->get_cart()[$key]['quantity']===2,'concurrent sharpening change is preserved');
// Real private checkout setup, shared fees and native source-session transfer.
StorefrontBooking::begin();$sourceSession=WC()->session;$sourceCart=WC()->cart;
$address=['address_1'=>'1 Synthetic Street','address_2'=>'','city'=>'Pittsburg','state'=>'CA','country'=>'US','postcode'=>'94565'];
$paid=Booking::create(array_replace($base,['mode'=>'prepaid_pickup_delivery','postal_code'=>'94565']),$owner,'sf-paid-'.Domain::id());$paid=Booking::submit($paid['id'],$owner,['customer'=>['name'=>'Synthetic buyer','email'=>'buyer@example.invalid'],'pickup_address'=>$address],true);Booking::checkout($paid['id'],$owner);$paid=Store::get($paid['id']);$_COOKIE['krev_booking_access']=Booking::accessToken($paid);BookingSession::prepare($paid,$owner,['billing'=>$address,'shipping'=>$address,'email'=>'buyer@example.invalid','payment_method'=>'stripe']);StorefrontBooking::complete($paid);
sfCheck(WC()->session!==$sourceSession,'payment uses isolated native session');sfCheck(count($sourceSession->get('cart'))===1 && isset($sourceSession->get('cart')[$gkey]),'paid transfer preserves ordinary physical cart');sfCheck(array_sum(array_column(WC()->cart->get_cart(),'quantity'))===4,'edited knife quantities copied to payment');sfCheck(Domain::cents(wc_format_decimal(WC()->cart->get_total('edit'),2))===3300,'three small plus one large plus $11 combo total $33 before tax');sfCheck(WC()->cart->get_shipping_total()==0,'parcel flat shipping is excluded');$fees=WC()->cart->get_fees();sfCheck(count($fees)===1 && reset($fees)->taxable && reset($fees)->amount==11,'one taxable $11 fee for all knives');sfCheck(!Booking::merchantVisible(Store::get($paid['id'])),'prepaid storefront request stays hidden before verified payment');sfCheck(empty(Store::get($paid['id'])['data']['order_id']),'preparation did not create a paid order');sfCheck(!StorefrontBooking::active(),'source context ends after transfer');
sfCheck(!wc_has_notice('Booking items changed. Review your booking before paying.','error'),'building multiple service lines creates no false changed-items warning');sfCheck(!WC()->session->get('krev_booking_cart_building'),'construction flag cleared before payment');
echo 'PASS: '.$checks." storefront assertions; no external payment or email.\n";ob_end_flush();
